[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php]
command=%(ENV_SUPERVISOR_PHP_COMMAND)s
user=%(ENV_SUPERVISOR_PHP_USER)s
environment=LARAVEL_SAIL="1"
stdout_logfile=/var/log/supervisor/php.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/var/log/supervisor/php-error.log
stderr_logfile_maxbytes=10MB

[include]
files=/etc/supervisor/conf.d/*.conf